### ISSUE TITLE
Russian translation of "minutes" in "x minutes ago" does not agree with some numbers

### ISSUE THREAD

**Issue by alanfgh** [Tatoeba/tatoeba2#1438]
Comment by Wezel on the Wall:

https://tatoeba.org/eng/wall/show_message/28145#message_28145

To elaborate on the comment: A Russian speaker tells me that "X minutes ago" should be "X минут назад" instead of "X минуты назад" for X = 5 to 20.

**Comment by alanfgh** [comment]
By the way, agreement with numbers in Russian is extremely complicated, as this discussion shows:

https://forum.wordreference.com/threads/all-slavic-languages-numbers-5-20-and-case.1756896/

**Comment by LokSyut** [comment]
Thanks for opening the ticket. To clarify a bit more, this is how the system should work:

1 minute ago – 1 минут**у** назад (or just “минуту назад“, without the number)

2-4 minutes ago – 2-4 минут**ы** назад

other numbers ending in 2-4, except 12-14 and numbers ending in 12-14: 22 минут**ы** назад, 23 минут**ы** назад, 34 минут**ы** назад 

with other numbers – X минут назад: 5 минут назад, 7 минут назад, 11 минут назад, 12 минут назад…

**Comment by RobinvanderVliet** [comment]
[This [page](http://www.unicode.org/cldr/charts/29/supplemental/language_plural_rules.html) contains the plural rules for a lot of languages, it might be useful.

**Comment by alanfgh** [comment]
Thanks for the information, everyone.

**Comment by explanacion** [comment]
The same problem for "days". 
We need:
1 day ago (and also 21, 31..., 101...) - 1 день назад
2 - 4 days ago (and also 22, 23, 24..., 32, 33, 34...) - 2-4 дня назад
with other numbers - 5 дней назад

**Comment by explanacion** [comment]
Hello, gillux. I’m afraid I couldn’t open your link. I registered on the website but I couldn’t join the team since there was no Russian language there.





От: gillux
Отправлено: 14 декабря 2018 г. в 20:29
Кому: Tatoeba/tatoeba2
Копия: Konstantin; Comment
Тема: Re: [Tatoeba/tatoeba2] Russian translation of "minutes" in "x minutesago" does not agree with some numbers (#1438)

We already have something to deal with Russian plural forms on Transifex.
For example, if you look at the translatable string "x days", you can see blue buttons on the top-right corner of the editable text area. These buttons allows you to switch between different translations of the same string depending on the number in it. English has two forms (singular and plural), hence the two buttons, while Russian has four. The names of the buttons are supposed to match the "category" column of this table.
You can try to update the translation and see how it shows on dev.tatoeba.org (it’s updated every 30 minutes).

**Comment by trang** [comment]
@explanacion I accepted your request to join the Transifex Russian team. You should now be able to open the link that gillux posted.

**Comment by trang** [comment]
@explanacion Note that I have switched the dev website to the cakephp-3 branch (https://tatoeba.org/eng/wall/show_message/30964#message_30964). We haven't solved fixed UI translations yet on that branch.

**Comment by jiru** [comment]
> To elaborate on the comment: A Russian speaker tells me that "X minutes ago" should be "X минут назад" instead of "X минуты назад" for X = 5 to 20.

I looks like the string is correct now:

![screenshot_2019-02-25 tatoeba](https://user-images.githubusercontent.com/5107734/53320504-d78b4780-3910-11e9-88b7-ab768f4be3c1.png)

@explanacion Can you confirm this problem is solved now?

**Comment by explanacion** [comment]
@jiru Yes, thank you. It's solved now.

**Comment by fjay69** [comment]
We still have an issue with days displaying. "Yesterday" is "Вчера", but this form is also uses for 21,31,41 etc. So instead "21 день назад" I see "Вчера".
