### ISSUE TITLE
Searching for some Hebrew items get a "search error" message.

### ISSUE THREAD

**Issue by ckjpn** [Tatoeba/tatoeba2#1445]
## The Problem

Searches for these Hebrew item results in a Search Error.

## Examples

5840774	heb	בחרנו בו בתור יו"ר.	fekundulo
https://tatoeba.org/eng/sentences/search?query=%D7%91%D7%AA%D7%95%D7%A8+%D7%99%D7%95%22%D7%A8&from=und&to=und

5840873	heb	הוא קיבל על עצמו את המנוי כיו"ר.	fekundulo
https://tatoeba.org/eng/sentences/search?query=+%D7%A2%D7%9C+%D7%A2%D7%A6%D7%9E%D7%95+%D7%90%D7%AA+%D7%94%D7%9E%D7%A0%D7%95%D7%99+%D7%9B%D7%99%D7%95%22%D7%A8&from=und&to=und

**Comment by trang** [comment]
This is related to #1405. It's because there's a double quote in the search string.

**Comment by ckjpn** [comment]
Perhaps there is some way you can escape the quote when searching for items in Hebrew.

While #1405 may be related, searching is pretty fundamental to taoteba.org, I think.

**Comment by jiru** [comment]
If I understand correctly, Hebrew uses the punctuation characters ["geresh" and "gershayim" which respectively look like "simple quote" and "double quote"](https://en.wikipedia.org/wiki/Hebrew_punctuation#Apostrophe_and_quotation_marks). As a result, people just use simple and double quote when writing Hebrew, because they don’t know how to type the proper characters geresh and gershayim.

Again, if I understand correctly, since geresh and gershayim are punctuation in Hebrew, they should be treated as words separators, like they currently are.

Eventually, this issue is not specific to Hebrew as it happens to anyone using, in a search, a punctuation character that happens to be a search operator, like the double quote is. So I think we can close this issue.

@alanfgh Since you know Hebrew better than I do, I’d like to have your opinion on this.

**Comment by alanfgh** [comment]
@jiru, your description of the problem is mostly correct, but geresh and gershayim should not be treated by Sphinx as word separators for the same reason that we don't treat an apostrophe in an English word like "can't" as a word separator. However, since genuine geresh and genuine gershayim are typed so rarely when people add Hebrew sentences, our treatment of these actual characters affects hardly any sentences.

The big problem is not with geresh (represented by most people with a single quote, which we don't treat as a word separator) but gershayim (represented by most people with a double quote, which we do). While the problem is theoretically not specific to Hebrew, and that we understand why it's happening, I don't think that constitutes a solid reason for closing the issue. It would be better to come up with an approach that lets people do the searches they want. This may require some thought and discussion.

**Comment by jiru** [comment]
Actually, Sphinx treats the apostrophe as a word separator. That is, it reads "can't" as two words, "can" and "t". Which is mostly harmless I think (except when looking up "can't don't" maybe), while it is appropriate in French, where a lot of prepositions merge with the following word, like "the elephant = l’éléphant" or "I admire you = je t’admire".

I think we need to always show results regardless of syntax errors. That is to say, if the query has a syntax error, treat it as a mere bag of words, ignoring search operators.

**Comment by alanfgh** [comment]
That makes sense.

**Comment by jiru** [comment]
@alanfgh I pushed a fix on [dev.tatoeba.org](https://dev.tatoeba.org/), can you try it out?

**Comment by alanfgh** [comment]
It works. The searches that you mentioned above, which still fail on the production website, succeed on the development website. Thanks!
