### ISSUE TITLE
Standard Moroccan Berber (zgh)

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#2601]
* Language name: Standard Moroccan Berber
* Language info: https://en.wikipedia.org/wiki/Standard_Moroccan_Berber
* ISO 639-3 code: ZGH
* Public List: https://tatoeba.org/eng/sentences_lists/show/169078
* Icon: https://imgur.com/a/ErdSo8Z
* Requested by: https://tatoeba.org/eng/user/profile/yaitelmouden

**Comment by jiru** [comment]
Note that we already have a language called Berber (ber) although it’s a kind of macrolanguage and it’s not part of iso639-3. I’m afraid that the similar name "Standard Moroccan Berber" might confuse some users.

**Comment by sabretou** [comment]
@jiru That is a possibility.

@RyckRichards To avoid confusions, let us use the ISO and Glottolog name for the language: Standard Moroccan Tamazight.

**Comment by RyckRichards** [comment]
Alright then.

**Comment by RyckRichards** [comment]
Done - https://github.com/Tatoeba/tatoeba2/pull/2606/commits/6892755a93d17a63228057d571f05ed0a3c048ea

**Comment by sabretou** [comment]
@RyckRichards You missed a 't' at the end of the name there. :)

**Comment by RyckRichards** [comment]
Oh thanks
