### ISSUE TITLE
Make it easier to remove a sentence from a list

### ISSUE THREAD

**Issue by RyckRichards** [Tatoeba/tatoeba2#895]
By [cueyayotl](https://tatoeba.org/eng/user/profile/cueyayotl)

> A way to remove a single sentence from a list, without having to browse through the list.
> 
> We now can see which lists the sentence belongs to. How about a link to remove the sentence from the list (if the list is ours, or is collaborative).
> 
> Also, language filter for lists.

**Comment by RyckRichards** [comment]
Requested by cueyayotl on [Tatoeba Day #10](https://tatoeba.org/eng/wall/show_message/24737#message_24737)

**Comment by ckjpn** [comment]
Likely the best way to do this would be to make it possible on a sentence's page to remove it from a list.

That's how I currently do it with this JavaScript bookmarklet.

javascript:var a%3Dwindow.prompt("Enter the list number to remove this sentence from")%3Bif(a!%3Dnull%26%26location.href.search(/tatoeba%5C.org%5C/.%2B%5C/sentences%5C/show%5C//)!%3D-1%26%26a.match(/%5E%5B0-9%5D%2B%24/)!%3Dnull)location.href%3Dlocation.href.replace("sentences/show","sentences_lists/remove_sentence_from_list")%2B"/"%2Ba%3B

**Comment by ckjpn** [comment]
I still think what I suggested in the previous comment might be the best approach.
It would be somewhat similar to how you remove favorite sentences from your favorites list.

**Comment by agrodet** [comment]
I think this is now solved in the new design. Not sure there is any reason to spend time implementing it in the old design.

**Comment by trang** [comment]
It's not completely solved. We should add a remove button next to the list on the sentence page. Because from the new design, you wouldn't be able to easily tell which of your lists the sentence has been added to.

![Screenshot_2020-03-18 Quando foi que vocês se casaram - Portuguese example sentence - Tatoeba](https://user-images.githubusercontent.com/221850/76977988-67de6500-6936-11ea-8dc2-7b803b8db957.png)

**Comment by jiru** [comment]
@trang I’m not sure I understand your explanation.

> from the new design, you wouldn't be able to easily tell which of your lists the sentence has been added to.

From the new design, I can click on the list button (in the sentence menu) to check which of my lists the sentence has been added to. From there, I can uncheck the box to remove it from a particular list of mine.

**Comment by trang** [comment]
Yes, true. I don't know anymore what exactly I was thinking 🤔 

My only guess is that I felt it was not intuitive that to remove a sentence from a list that is listed in the sidebar, one has to:
- open the list in the sentence
- search for the list
- then uncheck the checkbox

instead of:
- click on a X button next to the list name

**Comment by bakananbanjin** [comment]
Hi I got told to try me on this little problem.  (first i am absolutly new to javascript or cakephp, and even php)

I basicly got that you want something like next to the list list and x button to fast remove a selected sentences from a list. (
![image](https://user-images.githubusercontent.com/64922245/83634951-b3062c80-a5a3-11ea-86d6-62e1cf17a736.png)
)
I got the x button and an event listener who calls the following function:

![image](https://user-images.githubusercontent.com/64922245/83635857-38d6a780-a5a5-11ea-8385-3f3be9aedbab.png)


I orientied me on the weebroot/js/sentences_lists.remove_sentence_from_list (the function if you are in an List to remove the sentences.)
![image](https://user-images.githubusercontent.com/64922245/83636000-7cc9ac80-a5a5-11ea-9911-4128147609e8.png)


If i click on the x the event gets correctly handled (or at least the alert is done)
![image](https://user-images.githubusercontent.com/64922245/83635052-d92bcc80-a5a3-11ea-9574-b365d3869f11.png)

I think my problem is a simple missing of reference or something that i should have included but because I dont get it it would be appreciated, if someone could give me a hint or something.

**Comment by AndiPersti** [comment]
> Hi I got told to try me on this little problem. (first i am absolutly new to javascript or cakephp, and even php)

While you could use javascript (and thus avoid a redirect), for a first version it would suffice to add the `X` button and link it to the correct address on the server. The server will then redirect to the same page and thus it will be reloaded but with the list removed.

We do it like that already with tags on the same page (you need to be logged in at least as an `advanced_contributor` in order to add/remove tags).

So I suggest to look at the implementation for removing a tag. You're code should 1) add a link/button next to the list name and 2) a Controller function which handles the removing of the list in the database.

> I basicly got that you want something like next to the list list and x button to fast remove a selected sentences from a list.

Very good. That was the first step. :+1: 

> I think my problem is a simple missing of reference or something that i should have included but because I dont get it it would be appreciated, if someone could give me a hint or something.

For getting it to work using just javascript, you would need to have access to the sentence data. But since we are using AngularJS for the sentence component, it's not so easy to have access to the data in the sidebar.
